/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup BootstrapAssets;
extern const Sifteo::PinnedAssetImage BlackTile;
extern const Sifteo::AssetImage Backgrounds;
extern const Sifteo::PinnedAssetImage Bars[4];
extern const Sifteo::AssetAudio SfxAttach;
extern const Sifteo::AssetAudio SfxDetach;
extern const Sifteo::AssetAudio SfxConnect;
extern const Sifteo::AssetTracker Music;
